### ISSUE TITLE
README says 'not public'

### ISSUE THREAD

**Issue by lynnlangit** [nextstrain/monkeypox#1]
I see that you just committed to this repo.  Your README.md says 'this is not public', yet this GitHub Repo is public.  Just wanted to let you know, in case you forgot to set this GitHub Repo to private.

**Comment by trvrb** [comment]
Thanks @lynnlangit! We meant this as in there had not been a "public" analysis up at nextstrain.org. We now have https://nextstrain.org/monkeypox up. I'll adjust readme.
