### ISSUE TITLE
Will you be updating outbreak.fasta ?

### ISSUE THREAD

**Issue by tseemann** [nextstrain/monkeypox#13]
Just wondering if `ourbreak.fasta` will be updated with all the recent sequences in NCBI that are visible on the Nextstrain tree?

**Comment by rneher** [comment]
we are currently trying to figure out how we do this. At this point, the best way to access the sequences is probably through gen-spectrum

https://mpox.gen-spectrum.org/explore

or LAPIS like so:
https://github.com/nextstrain/monkeypox/blob/lapis2/workflow/snakemake_rules/download_via_lapis.smk

**Comment by tseemann** [comment]
Thanks @rneher - hope you and the team are keeping well.
