### ISSUE TITLE
/usr/bin/bash: line 1: tsv-filter: command not found

### ISSUE THREAD

**Issue by Pregabaline** [nextstrain/monkeypox#138]
Running the monkeypox pipeline the workflow errors out with the "tsv-filter" not found. Not sure in which script file or nextstrain package this command comes from. Am I missing a specific extra Nextstrain package or something that I should have installed?

**Comment by j23414** [comment]
Hi @Pregabaline! Looks like you're missing the [tsv-utils package](https://github.com/eBay/tsv-utils): 

* [tsv-filter](https://github.com/eBay/tsv-utils/blob/master/docs/tool_reference/tsv-filter.md)

Can you say a bit more about your computing environment or maybe which install method in [https://docs.nextstrain.org/en/latest/install.html](https://docs.nextstrain.org/en/latest/install.html)?

**Comment by corneliusroemer** [comment]
`tsv-utils` can be installed via bioconda `conda install -c bioconda tsv-utils`, it's automatically part of the Nextstrain docker container and our managed conda runtime.

It's _not_ auto installed when using the ambient command we used to have in docs. But we're phasing this out anyways I think.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/25161793/205759635-dc5b68f7-6d0e-498b-ba36-5424c282822f.png">
