### ISSUE TITLE
ingest: run NextClade and include in output files

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/monkeypox#37]
### Context
Run sequences through NextClade and include output in the final metadata TSV so that it can be imported into LAPIS. 

### Description
This is currently a [multi-rule process in ncov-ingest](https://github.com/nextstrain/ncov-ingest/blob/1eb377df20670a896a3942b1a8eed78df15ccd18/Snakefile#L163-L332) because we keep a cache of the previous runs. We can adopt a similar process here as well, but be aware of pitfalls described in https://github.com/nextstrain/ncov-ingest/pull/218

**Comment by corneliusroemer** [comment]
Resolved by #58
