### ISSUE TITLE
can not see the map?

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [nextstrain/monkeypox#46]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/46078579/172800983-6237404c-bd58-4f95-aaf7-ba2d6e093817.png">

**Comment by emmahodcroft** [comment]
Hi @LiXingguangBrandonStark - I'm afraid this doesn't look like the Nextstrain website, so I'm not sure we can help with this bug. Can you give the URL you are trying to view?
