### ISSUE TITLE
Masking more sites

### ISSUE THREAD

**Issue by babarlelephant** [nextstrain/monkeypox#56]
Hi, in my tree I am masking 146773;146927

![image](https://user-images.githubusercontent.com/6537565/173695038-3dd6d7df-feb2-4f33-8f8e-a8f75e9d565c.png)

and 169733:169795

![image](https://user-images.githubusercontent.com/6537565/173695352-e19227c2-260b-41e0-bf0f-7e8e0f9fcc9d.png)

thereby eliminating the 3 non-Apobec mutations in internal branches that you get in https://nextstrain.org/monkeypox/mpxv?c=gt-nuc_146895,169756,169760&label=clade:B.1

(the pictures are from my mafft --addfragments alignment from which I remove the columns gapped in UK_P2, the masked coordinates apply to the latter set of columns)

**Comment by rneher** [comment]
Thanks, @babarlelephant! It probably makes sense to mask these as well. I'll look into it.

**Comment by rneher** [comment]
I have added these to the mask of the mpxv build.
