### ISSUE TITLE
The geographic map is not appearing behind the geolocations in the mapbox image on our installed server as it does on the nexstrain.org server at https://nextstrain.org/monkeypox/mpxv?f_host=Homo%20sapiens 

### ISSUE THREAD

**Issue by DrB-S** [nextstrain/monkeypox#88]
### Current Behavior
The geographic map is not appearing behind the geolocations in the mapbox image on our installed server as it does on the nexstrain.org server at https://nextstrain.org/monkeypox/mpxv?f_host=Homo%20sapiens 

### Expected behavior
A clear and concise description of what you expected to happen instead.

### How to reproduce
Steps to reproduce the current behavior:
1. Installed nextstrain/monkeypox today (28 June 2022) using Docker on our Amazon Server (with nextstrain.cli 3.0.5):
  
  nextstrain-cli/bin/nextstrain  build --docker . data/sequences.fasta data/metadata.tsv

  nextstrain-cli/bin/nextstrain  build --docker --cpus 50 . --configfile config/config_mpxv.yaml

  nextstrain-cli/bin/nextstrain build --docker --cpus 50 . --configfile config/config_hmpxv1.yaml

### Visualize results

nextstrain-cli/bin/nextstrain view auspice/ --allow-remote-access

In Chrome browser:

http://awsgenomep:4000/monkeypox/mpxv?f_host=Homo%20sapiens

### Possible solution
(optional)

### Your environment: if browsing Nextstrain online
 - Operating system: 
 - Browser:

### Your environment: if running Nextstrain locally
 - Operating system: Amazon Linux 2 AMI
 - Browser: Chrome
 - Version (e.g. `auspice 2.7.0`):

### Additional context
![Screen Shot 2022-06-28 at 12 22 24 PM](https://user-images.githubusercontent.com/90658214/176267971-f5c5a466-130b-4bc5-9846-2d6ce8b89ccb.png)

**Comment by jameshadfield** [comment]
Hi @DrB-S  -- could you try the solutions in this discussion thread: https://discussion.nextstrain.org/t/build-with-newest-nextstrain-ncov-has-api-requests-to-mapbox-403-forbidden/396/12 & if those don't solve the issue please re-open!
